<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <RootNamespace>UserManagement.Blazor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserManagement.Contracts\UserManagement.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Material.Blazor" Version="5.3.28" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" PrivateAssets="all" />
  </ItemGroup>

</Project>
