<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>UserManagement.Messaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserManagement.Repository.Sql\UserManagement.Repository.Sql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
  </ItemGroup>

</Project>
